# Save best runs and add to set with best runs from all batches
library(gdata)
library(tibble)
# Before executing, load the new batch into the environment
source("C:/Users/kevin/Documents/INFEWS/SWAT+R/OptimalSearch_super.R")
bestperf_new <- super_iter
bestperf_new$simulation <- bestperf_new$simulation[-c(7,8,9,10)] # get ride of tile_flow etc. b/c don't have "date" column
bestperf_new$parameter$values <- bestperf_new$parameter$values[optimal_runs,]
bestperf_new$simulation <-lapply(bestperf_new$simulation, "[",  c(1,optimal_runs+1)) # for first batch

# For first batch
# best_perf <- bestperf_new # for first batch
# For other batches - combine with previous batches
best_perf$parameter$values <- full_join(best_perf$parameter$values, bestperf_new$parameter$values)
best_perf$simulation$q_out_6<-merge(x=best_perf$simulation$q_out_6,y=bestperf_new$simulation$q_out_6,by.x="date",by.y = "date",all= T)
best_perf$simulation$q_out_6 <- as_tibble(best_perf$simulation$q_out_6)
best_perf$simulation$q_out_14<-merge(x=best_perf$simulation$q_out_14,y=bestperf_new$simulation$q_out_14,by.x="date",by.y = "date",all= T)
best_perf$simulation$q_out_14 <- as_tibble(best_perf$simulation$q_out_14)
best_perf$simulation$q_out_23<-merge(x=best_perf$simulation$q_out_23,y=bestperf_new$simulation$q_out_23,by.x="date",by.y = "date",all= T)
best_perf$simulation$q_out_23 <- as_tibble(best_perf$simulation$q_out_23)
best_perf$simulation$q_out_24<-merge(x=best_perf$simulation$q_out_24,y=bestperf_new$simulation$q_out_24,by.x="date",by.y = "date",all= T)
best_perf$simulation$q_out_24 <- as_tibble(best_perf$simulation$q_out_24)
best_perf$simulation$q_out_25<-merge(x=best_perf$simulation$q_out_25,y=bestperf_new$simulation$q_out_25,by.x="date",by.y = "date",all= T)
best_perf$simulation$q_out_25 <- as_tibble(best_perf$simulation$q_out_25)
best_perf$simulation$q_out_26<-merge(x=best_perf$simulation$q_out_26,y=bestperf_new$simulation$q_out_26,by.x="date",by.y = "date",all= T)
best_perf$simulation$q_out_26 <- as_tibble(best_perf$simulation$q_out_26)
best_perf$simulation$sed_out_14<-merge(x=best_perf$simulation$sed_out_14,y=bestperf_new$simulation$sed_out_14,by.x="date",by.y = "date",all= T)
best_perf$simulation$sed_out_14 <- as_tibble(best_perf$simulation$sed_out_14)
best_perf$simulation$sed_out_23<-merge(x=best_perf$simulation$sed_out_23,y=bestperf_new$simulation$sed_out_23,by.x="date",by.y = "date",all= T)
best_perf$simulation$sed_out_23 <- as_tibble(best_perf$simulation$sed_out_23)
best_perf$simulation$sed_out_24<-merge(x=best_perf$simulation$sed_out_24,y=bestperf_new$simulation$sed_out_24,by.x="date",by.y = "date",all= T)
best_perf$simulation$sed_out_24 <- as_tibble(best_perf$simulation$sed_out_24)
best_perf$simulation$sed_out_25<-merge(x=best_perf$simulation$sed_out_25,y=bestperf_new$simulation$sed_out_25,by.x="date",by.y = "date",all= T)
best_perf$simulation$sed_out_25 <- as_tibble(best_perf$simulation$sed_out_25)
best_perf$simulation$sed_out_26<-merge(x=best_perf$simulation$sed_out_26,y=bestperf_new$simulation$sed_out_26,by.x="date",by.y = "date",all= T)
best_perf$simulation$sed_out_26 <- as_tibble(best_perf$simulation$sed_out_26)
best_perf$simulation$tss_out_14<-merge(x=best_perf$simulation$tss_out_14,y=bestperf_new$simulation$tss_out_14,by.x="date",by.y = "date",all= T)
best_perf$simulation$tss_out_14 <- as_tibble(best_perf$simulation$tss_out_14)
best_perf$simulation$tss_out_23<-merge(x=best_perf$simulation$tss_out_23,y=bestperf_new$simulation$tss_out_23,by.x="date",by.y = "date",all= T)
best_perf$simulation$tss_out_23 <- as_tibble(best_perf$simulation$tss_out_23)
best_perf$simulation$tss_out_24<-merge(x=best_perf$simulation$tss_out_24,y=bestperf_new$simulation$tss_out_24,by.x="date",by.y = "date",all= T)
best_perf$simulation$tss_out_24 <- as_tibble(best_perf$simulation$tss_out_24)
best_perf$simulation$tss_out_25<-merge(x=best_perf$simulation$tss_out_25,y=bestperf_new$simulation$tss_out_25,by.x="date",by.y = "date",all= T)
best_perf$simulation$tss_out_25 <- as_tibble(best_perf$simulation$tss_out_25)
best_perf$simulation$tss_out_26<-merge(x=best_perf$simulation$tss_out_26,y=bestperf_new$simulation$tss_out_26,by.x="date",by.y = "date",all= T)
best_perf$simulation$tss_out_26 <- as_tibble(best_perf$simulation$tss_out_26)
best_perf$simulation$res_sed_stor<-merge(x=best_perf$simulation$res_sed_stor,y=bestperf_new$simulation$res_sed_stor,by.x="date",by.y = "date",all= T)
best_perf$simulation$res_sed_stor <- as_tibble(best_perf$simulation$res_sed_stor)
best_perf$simulation$res_flo_stor<-merge(x=best_perf$simulation$res_flo_stor,y=bestperf_new$simulation$res_flo_stor,by.x="date",by.y = "date",all= T)
best_perf$simulation$res_flo_stor <- as_tibble(best_perf$simulation$res_flo_stor)
best_perf$simulation$orgp_out_14<-merge(x=best_perf$simulation$orgp_out_14,y=bestperf_new$simulation$orgp_out_14,by.x="date",by.y = "date",all= T)
best_perf$simulation$orgp_out_14 <- as_tibble(best_perf$simulation$orgp_out_14)
best_perf$simulation$orgp_out_23<-merge(x=best_perf$simulation$orgp_out_23,y=bestperf_new$simulation$orgp_out_23,by.x="date",by.y = "date",all= T)
best_perf$simulation$orgp_out_23 <- as_tibble(best_perf$simulation$orgp_out_23)
best_perf$simulation$orgp_out_24<-merge(x=best_perf$simulation$orgp_out_24,y=bestperf_new$simulation$orgp_out_24,by.x="date",by.y = "date",all= T)
best_perf$simulation$orgp_out_24 <- as_tibble(best_perf$simulation$orgp_out_24)
best_perf$simulation$orgp_out_25<-merge(x=best_perf$simulation$orgp_out_25,y=bestperf_new$simulation$orgp_out_25,by.x="date",by.y = "date",all= T)
best_perf$simulation$orgp_out_25 <- as_tibble(best_perf$simulation$orgp_out_25)
best_perf$simulation$orgp_out_26<-merge(x=best_perf$simulation$orgp_out_26,y=bestperf_new$simulation$orgp_out_26,by.x="date",by.y = "date",all= T)
best_perf$simulation$orgp_out_26 <- as_tibble(best_perf$simulation$orgp_out_26)
best_perf$simulation$minpa_out_14<-merge(x=best_perf$simulation$minpa_out_14,y=bestperf_new$simulation$minpa_out_14,by.x="date",by.y = "date",all= T)
best_perf$simulation$minpa_out_14 <- as_tibble(best_perf$simulation$minpa_out_14)
best_perf$simulation$minpa_out_23<-merge(x=best_perf$simulation$minpa_out_23,y=bestperf_new$simulation$minpa_out_23,by.x="date",by.y = "date",all= T)
best_perf$simulation$minpa_out_23 <- as_tibble(best_perf$simulation$minpa_out_23)
best_perf$simulation$minpa_out_24<-merge(x=best_perf$simulation$minpa_out_24,y=bestperf_new$simulation$minpa_out_24,by.x="date",by.y = "date",all= T)
best_perf$simulation$minpa_out_24 <- as_tibble(best_perf$simulation$minpa_out_24)
best_perf$simulation$minpa_out_25<-merge(x=best_perf$simulation$minpa_out_25,y=bestperf_new$simulation$minpa_out_25,by.x="date",by.y = "date",all= T)
best_perf$simulation$minpa_out_25 <- as_tibble(best_perf$simulation$minpa_out_25)
best_perf$simulation$minpa_out_26<-merge(x=best_perf$simulation$minpa_out_26,y=bestperf_new$simulation$minpa_out_26,by.x="date",by.y = "date",all= T)
best_perf$simulation$minpa_out_26 <- as_tibble(best_perf$simulation$minpa_out_26)
best_perf$simulation$minps_out_14<-merge(x=best_perf$simulation$minps_out_14,y=bestperf_new$simulation$minps_out_14,by.x="date",by.y = "date",all= T)
best_perf$simulation$minps_out_14 <- as_tibble(best_perf$simulation$minps_out_14)
best_perf$simulation$minps_out_23<-merge(x=best_perf$simulation$minps_out_23,y=bestperf_new$simulation$minps_out_23,by.x="date",by.y = "date",all= T)
best_perf$simulation$minps_out_23 <- as_tibble(best_perf$simulation$minps_out_23)
best_perf$simulation$minps_out_24<-merge(x=best_perf$simulation$minps_out_24,y=bestperf_new$simulation$minps_out_24,by.x="date",by.y = "date",all= T)
best_perf$simulation$minps_out_24 <- as_tibble(best_perf$simulation$minps_out_24)
best_perf$simulation$minps_out_25<-merge(x=best_perf$simulation$minps_out_25,y=bestperf_new$simulation$minps_out_25,by.x="date",by.y = "date",all= T)
best_perf$simulation$minps_out_25 <- as_tibble(best_perf$simulation$minps_out_25)
best_perf$simulation$minps_out_26<-merge(x=best_perf$simulation$minps_out_26,y=bestperf_new$simulation$minps_out_26,by.x="date",by.y = "date",all= T)
best_perf$simulation$minps_out_26 <- as_tibble(best_perf$simulation$minps_out_26)
best_perf$simulation$solp_out_14<-merge(x=best_perf$simulation$solp_out_14,y=bestperf_new$simulation$solp_out_14,by.x="date",by.y = "date",all= T)
best_perf$simulation$solp_out_14 <- as_tibble(best_perf$simulation$solp_out_14)
best_perf$simulation$solp_out_23<-merge(x=best_perf$simulation$solp_out_23,y=bestperf_new$simulation$solp_out_23,by.x="date",by.y = "date",all= T)
best_perf$simulation$solp_out_23 <- as_tibble(best_perf$simulation$solp_out_23)
best_perf$simulation$solp_out_24<-merge(x=best_perf$simulation$solp_out_24,y=bestperf_new$simulation$solp_out_24,by.x="date",by.y = "date",all= T)
best_perf$simulation$solp_out_24 <- as_tibble(best_perf$simulation$solp_out_24)
best_perf$simulation$solp_out_25<-merge(x=best_perf$simulation$solp_out_25,y=bestperf_new$simulation$solp_out_25,by.x="date",by.y = "date",all= T)
best_perf$simulation$solp_out_25 <- as_tibble(best_perf$simulation$solp_out_25)
best_perf$simulation$solp_out_26<-merge(x=best_perf$simulation$solp_out_26,y=bestperf_new$simulation$solp_out_26,by.x="date",by.y = "date",all= T)
best_perf$simulation$solp_out_26 <- as_tibble(best_perf$simulation$solp_out_26)
best_perf$simulation$res_orgp_stor<-merge(x=best_perf$simulation$res_orgp_stor,y=bestperf_new$simulation$res_orgp_stor,by.x="date",by.y = "date",all= T)
best_perf$simulation$res_orgp_stor <- as_tibble(best_perf$simulation$res_orgp_stor)
best_perf$simulation$res_minpa_stor<-merge(x=best_perf$simulation$res_minpa_stor,y=bestperf_new$simulation$res_minpa_stor,by.x="date",by.y = "date",all= T)
best_perf$simulation$res_minpa_stor <- as_tibble(best_perf$simulation$res_minpa_stor)
best_perf$simulation$res_minps_stor<-merge(x=best_perf$simulation$res_minps_stor,y=bestperf_new$simulation$res_minps_stor,by.x="date",by.y = "date",all= T)
best_perf$simulation$res_minps_stor <- as_tibble(best_perf$simulation$res_minps_stor)
best_perf$simulation$res_solp_stor<-merge(x=best_perf$simulation$res_solp_stor,y=bestperf_new$simulation$res_solp_stor,by.x="date",by.y = "date",all= T)
best_perf$simulation$res_solp_stor <- as_tibble(best_perf$simulation$res_solp_stor)
best_perf$simulation$sed_resconc<-merge(x=best_perf$simulation$sed_resconc,y=bestperf_new$simulation$sed_resconc,by.x="date",by.y = "date",all= T)
best_perf$simulation$sed_resconc <- as_tibble(best_perf$simulation$sed_resconc)
best_perf$simulation$totalP_14<-merge(x=best_perf$simulation$totalP_14,y=bestperf_new$simulation$totalP_14,by.x="date",by.y = "date",all= T)
best_perf$simulation$totalP_14 <- as_tibble(best_perf$simulation$totalP_14)
best_perf$simulation$totalP_26<-merge(x=best_perf$simulation$totalP_26,y=bestperf_new$simulation$totalP_26,by.x="date",by.y = "date",all= T)
best_perf$simulation$totalP_26 <- as_tibble(best_perf$simulation$totalP_26)
best_perf$simulation$totalP_23<-merge(x=best_perf$simulation$totalP_23,y=bestperf_new$simulation$totalP_23,by.x="date",by.y = "date",all= T)
best_perf$simulation$totalP_23 <- as_tibble(best_perf$simulation$totalP_23)
best_perf$simulation$totalP_24<-merge(x=best_perf$simulation$totalP_24,y=bestperf_new$simulation$totalP_24,by.x="date",by.y = "date",all= T)
best_perf$simulation$totalP_24 <- as_tibble(best_perf$simulation$totalP_24)
best_perf$simulation$totalP_25<-merge(x=best_perf$simulation$totalP_25,y=bestperf_new$simulation$totalP_25,by.x="date",by.y = "date",all= T)
best_perf$simulation$totalP_25 <- as_tibble(best_perf$simulation$totalP_25)
best_perf$simulation$totalP_resconc<-merge(x=best_perf$simulation$totalP_resconc,y=bestperf_new$simulation$totalP_resconc,by.x="date",by.y = "date",all= T)
best_perf$simulation$totalP_resconc <- as_tibble(best_perf$simulation$totalP_resconc)
best_perf$simulation$solP_resconc<-merge(x=best_perf$simulation$solP_resconc,y=bestperf_new$simulation$solP_resconc,by.x="date",by.y = "date",all= T)
best_perf$simulation$solP_resconc <- as_tibble(best_perf$simulation$solP_resconc)

# Remove all variables except best_perf
rm(list=setdiff(ls(), "best_perf"))

# Analysis
library(vioplot)
# num_analyze_opt <- length(best_perf$parameter$values$bd)
# values_opt <- best_perf$parameter$values[,-c(45)]
num_analyze_opt <- length(optimal_runs)
values_opt <- best_perf$parameter$values[optimal_runs,-c(45)]
N <- length(values_opt[1,])
for(param in 1:N)
{
  #boxplot(values_opt[,param])
  vioplot(values_opt[,param])
}

write.csv(values_opt, "C:\\Users\\kevin\\Documents\\INFEWS\\SWAT+R\\100paramsets.csv", row.names=TRUE)

# Figures for SI
vioplot(values_opt[,2], names="", cex.axis = 2, cex.main = 3, main='surlag')
vioplot(values_opt[,26], names="", cex.axis = 2, cex.main = 3,main='kod_a5')
vioplot(values_opt[,31], names="", cex.axis = 2, cex.main = 3,main='stl_vel')
vioplot(values_opt[,36], names="", cex.axis = 2, cex.main = 3,main='srpm2')
vioplot(values_opt[,40], names="", cex.axis = 2, cex.main = 3,main='srpm2_swq')
vioplot(values_opt[,41], names="", cex.axis = 2, cex.main = 3,main='adskeq_swq')

### OLD, DONT USE###
# best_perf$simulation$q_out_6 <- c(best_perf$simulation$q_out_6, bestperf_new$simulation$q_out_6)
# allruns <- best_perf$simulation[3]
# names(allruns)<- "var"
# allruns <- as_tibble(allruns)
# newruns <- bestperf_new$simulation[3]
# names(newruns)<- "var"
# newruns <- as_tibble(newruns)
# best_perf$simulation[3]<-merge(x=allruns,y=newruns,by.x="var.date",by.y = "var.date",all= T)
# best_perf$simulation[3] <- as_tibble(best_perf$simulation[3])
# 
# best_perf$simulation[3]<-merge(x=best_perf$simulation[3],y=bestperf_new$simulation[3],by.x="date",by.y = "date",all= T)
