library(SWATplusR)
library(lhs)
library(hydroGOF)
library(dplyr)
library(lubridate)
library(tidyr)
library(purrr)
library(ggplot2)
library(hydroTSM)
library(stringr)
library(car)
library(twosamples)

source("C:/Users/kevin/Documents/INFEWS/SWAT+R/SWAT+R_supercal.R")
source("C:/Users/kevin/Documents/INFEWS/SWAT+R/SWAT+R_caldata.R")
source("C:/Users/kevin/Documents/INFEWS/SWAT+R/SWAT+R_postprocessing.R")
source("C:/Users/kevin/Documents/INFEWS/SWAT+R/Evaluate_super.R")
source("C:/Users/kevin/Documents/INFEWS/SWAT+R/CramerVonMises_super.R")
source("C:/Users/kevin/Documents/INFEWS/SWAT+R/OptimalSearch_super.R")
source("C:/Users/kevin/Documents/INFEWS/SWAT+R/SWAT+R_AnalyzeOpt.R")
save.image("~/INFEWS/SWAT+R/SuperCal_test_postanalysis.RData") # update iteration number
